project:
  type: book

book:
  title: "WS 23/24 Numerics Notes"
  author: "Igor Dimitrov"
  date: "10/30/2023"
  chapters:
    - index.qmd
    - floating/floating.qmd
  downloads: pdf

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



